
before_install:
  - pip install codecov
after_success:
  - codecov
language: python
python:
  
  - "2.7"
  
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script: "python calculator.py test"
script: "python test_calculator.py test"
