
language: python
python:  
  - "2.7"  
# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
  - pip install codecov
# command to run tests
script: "py.test"
#script: "python test_calculator.py"

after_success:
  - codecov