
language: python
python:  
  - "2.7"  
# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
  - pip install codecov
after_success:
  - codecov
# command to run tests
script: "py.test"

